---
# tasks/main.yml
- name: Detect distribution version and details
  ansible.builtin.import_tasks: detect_distribution.yml
  tags: always

- name: Include repository templates
  ansible.builtin.include_vars:
    file: repo_templates.yml
    name: _repo_templates

- name: Set default repo list based on OS facts
  ansible.builtin.set_fact:
    _default_awesome_repo_list: "{{ _repo_templates[ansible_distribution][ansible_distribution_version] | default(_repo_templates[ansible_distribution][ansible_distribution_major_version] | default([])) }}"
  when: 
    - ansible_distribution in _repo_templates
    - ansible_distribution_version in _repo_templates[ansible_distribution] or ansible_distribution_major_version in _repo_templates[ansible_distribution]

- name: Manage repositories
  ansible.builtin.import_tasks: manage_repositories.yml
  tags:
    - awesome_repo
    - repos

- name: Install packages (optimized)
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - awesome_pkg_install
    - packages
